// 39-vue-cli-app/src/components/TodoList.vue
<template>
	<ul>
		<Todo-Item
			v-for="(dumbThing, i) in todos"
			v-bind:key="i"
			v-bind:item="dumbThing"
		/>
	</ul>
</template>

<script>
import TodoItem from './TodoItem'

export default {
	name: 'Todo-List',
	components: {
		TodoItem,
	},
	props: ['todos'],
	methods: {
	},
}
</script>

<style>
</style>

// 43-react-todo/src/components/TodoList.js
import React from "react";
import TodoItem from "./TodoItem";

const TodoList = (props) => {

	const todoItems = props.todos.map(todoItem => {
		return (
			<TodoItem
				todo={todoItem}
				key={todoItem.id}
				onDelete={props.onTodoItemDelete}
				onToggle={props.onTodoItemToggle}
			/>
		)
	})

	return (
		<ul className="todo-list">
			{todoItems}
		</ul>
	)
}

export default TodoList
